// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptDisclaimer() {
  return window['go']['main']['App']['AcceptDisclaimer']();
}

export function AddAccount(arg1) {
  return window['go']['main']['App']['AddAccount'](arg1);
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function GetAccountList() {
  return window['go']['main']['App']['GetAccountList']();
}

export function GetAiTypes() {
  return window['go']['main']['App']['GetAiTypes']();
}

export function GetAllProgress() {
  return window['go']['main']['App']['GetAllProgress']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetPlatforms() {
  return window['go']['main']['App']['GetPlatforms']();
}

export function GetProgress(arg1) {
  return window['go']['main']['App']['GetProgress'](arg1);
}

export function ImportConfigFile() {
  return window['go']['main']['App']['ImportConfigFile']();
}

export function IsDisclaimerAccepted() {
  return window['go']['main']['App']['IsDisclaimerAccepted']();
}

export function LoginCheck(arg1) {
  return window['go']['main']['App']['LoginCheck'](arg1);
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2);
}

export function PauseBrush(arg1) {
  return window['go']['main']['App']['PauseBrush'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartAllBrush() {
  return window['go']['main']['App']['StartAllBrush']();
}

export function StartBatchBrush(arg1) {
  return window['go']['main']['App']['StartBatchBrush'](arg1);
}

export function StartBrush(arg1) {
  return window['go']['main']['App']['StartBrush'](arg1);
}

export function StopBrush(arg1) {
  return window['go']['main']['App']['StopBrush'](arg1);
}

export function ToggleMaximizeWindow() {
  return window['go']['main']['App']['ToggleMaximizeWindow']();
}

export function UpdateAccount(arg1) {
  return window['go']['main']['App']['UpdateAccount'](arg1);
}
