// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptDisclaimer():Promise<void>;

export function AddAccount(arg1:string):Promise<string>;

export function CloseWindow():Promise<void>;

export function DeleteAccount(arg1:string):Promise<string>;

export function GetAccountList():Promise<string>;

export function GetAiTypes():Promise<string>;

export function GetAllProgress():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<string>;

export function GetPlatforms():Promise<string>;

export function GetProgress(arg1:string):Promise<string>;

export function ImportConfigFile():Promise<string>;

export function IsDisclaimerAccepted():Promise<boolean>;

export function LoginCheck(arg1:string):Promise<string>;

export function MinimizeWindow():Promise<void>;

export function OpenFileDialog(arg1:string,arg2:string):Promise<string>;

export function PauseBrush(arg1:string):Promise<string>;

export function QuitApp():Promise<void>;

export function SaveConfig(arg1:string):Promise<string>;

export function ShowWindow():Promise<void>;

export function StartAllBrush():Promise<string>;

export function StartBatchBrush(arg1:string):Promise<string>;

export function StartBrush(arg1:string):Promise<string>;

export function StopBrush(arg1:string):Promise<string>;

export function ToggleMaximizeWindow():Promise<void>;

export function UpdateAccount(arg1:string):Promise<string>;
